# Generated by Django 3.2.14 on 2022-07-23 08:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 8, 22, 56, 866091, tzinfo=utc)),
        ),
    ]
