# Generated by Django 3.2.14 on 2022-07-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_customer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Ready')], default='Draft', max_length=10),
        ),
    ]
